name: deploy to kuroshibaz server

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

#      - name: Cache Go dependencies
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/go/pkg/mod
#            ~/.cache/go-build
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build the Go App
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o kz_api-linux-x64 ./bootstrap/*.go

      - name: Save built binary
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: kz_api-linux-x64

  docker_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download built binary
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Login to Gitlab Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t registry.gitlab.com/kuroshibaz/kuroshibaz-api:1.0.1 .

      - name: Push Docker image to DigitalOcean Container Registry
        run: |
          docker push registry.gitlab.com/kuroshibaz/kuroshibaz-api:1.0.1

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying..."
            echo "${{ secrets.GITLAB_REGISTRY_PASSWORD }}" | docker login registry.gitlab.com -u "${{ secrets.GITLAB_REGISTRY_USERNAME }}" --password-stdin
            docker pull registry.gitlab.com/kuroshibaz/kuroshibaz-api:1.0.1