name: deploy to kuroshibaz server

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

      - name: Cache Go dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build the Go App
        run: |
          go build -o kz_api-linux-x64 boostrap/*.go
          

  docker_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t registry.digitalocean.com/kuroshibaz/kuroshibaz-api:1.0.0

      - name: Push Docker image to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/kuroshibaz/kuroshibaz-api:1.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying..."
            docker pull registry.digitalocean.com/kuroshibaz/kuroshibaz-api:1.0.0